import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppSidebar from "@/components/sidebar";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} text-sm antialiased text-stone-950 dark:text-stone-100 flex min-h-svh`}
      >
        <AppSidebar />
        <Toaster position="top-center" closeButton />
        <div className="pl-0 p-3 grow flex flex-col">
          <div className="dark:bg-[#1f1f1f] border dark:border-neutral-500/10 shadow-md flex flex-col grow rounded-2xl">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
